services:
  build:
    build:
      context: .
      dockerfile: Dockerfile
    # command: npx tailwindcss -i ./frontend/static/input.css -o ./frontend/static/output.css --watch
    tty: true
    ports:
      - "8080:8080"